### ISSUE TITLE
Add indefinite (as opposed to nextTransition) holds?

### ISSUE THREAD

**Issue by chobo997** [FlyingDiver/Indigo-Ecobee-2#1]
Quickly re: climate holds: I had modified the original Ecobee plugin to set an indefinite away hold as opposed to an away until nextTransition hold. This is extremely useful if you're away for several hours or days. Could be a nice addition for a lot of folks. Thanks for the great plugin and your consideration!

**Comment by FlyingDiver** [comment]
Well, if I put in a choice, I'll probably put them all in.

When you modified the original, did you make it configurable or did you just make all holds indefinite?

**Comment by chobo997** [comment]
Just made them all indefinite and used the resume feature to get back on schedule.

**Comment by FlyingDiver** [comment]
OK, thanks.  I'll have to think about that.

**Comment by FlyingDiver** [comment]
Try this version:  https://github.com/FlyingDiver/Indigo-Ecobee-2/releases/tag/2.1.0

**Comment by chobo997** [comment]
Just tested and working as expected. Thank you! My preferred hold type is nextTransition unless I'm setting an away hold. So... I do the following with an away scene: set hold type: indefinite, activate comfort setting: away, set hold type: nextTransition. Works perfectly, but is there a more direct way to do this?

**Comment by FlyingDiver** [comment]
I can probably add hold type as an option on the activate comfort setting action.

**Comment by chobo997** [comment]
That option might be a bit more obvious/user-friendly, but definitely not necessary.

**Comment by FlyingDiver** [comment]
Can you test 2.1.3. for this request?  Please set up an action to set the climate type before you install this version, and verify it still works the way you expect.  Then set up a new action with your preferred hold type and test that.

**Comment by chobo997** [comment]
Working exactly as expected. Thanks for implementing this. One thing to note: looks like both the old and the new methods exist in 2.1.3. Imagine you will have that resolved once this enhancement is released. Thanks again, Joe.

**Comment by FlyingDiver** [comment]
I was planning on leaving both in.  Is there a reason to take the other one out?

**Comment by chobo997** [comment]
That works. How persistent was the old option? Does it apply to all future holds or just for a certain period of time? They do behave slightly differently — might be helpful to briefly document the differences.

**Comment by FlyingDiver** [comment]
The other sets the default for that thermostat.  For any kind of hold, but it would really only apply to temp changes since the climate request now has it's own hold selection.

**Comment by FlyingDiver** [comment]
Done in 2.1.4
