### ISSUE TITLE
Updatable error after upgrade

### ISSUE THREAD

**Issue by mrstacey1284** [FlyingDiver/Indigo-Ecobee-2#10]
Thank you for all you hard work on this plugin as well as your full library. I love using indigo to mange my house and couldn't do it without all the work you put into you plugins!

I just upgraded to version 2.2.4 and started receiving the following error in the log: 
`Ecobee 2 Error                  updatable: Error obtaining ecobee account object`

Ive attempted to re-authenticate and re-install but have had no lock resolving it. The plugin seems to be working as intended, but it writes this error every 15min. When viewing the Ecobee account device it says it was updated yesterday at 2am and all Ecobee devices have been updated within the last few minutes.

**Comment by FlyingDiver** [comment]
Can you enable debug level logging and then post the entries before the error appears?

**Comment by mrstacey1284** [comment]
As soon as I enabled debuting this showed up in the log:

`Oct 27, 2020 at 12:18:12 PM
   Ecobee 2 Debug                  logLevel = 10
   Ecobee 2 Debug                  updateFrequency = 900.0
   Ecobee 2 Debug                  setting temperature scale to F
   Ecobee 2 Debug                  Ecobee Account (1064672344): Ecobee Account Update OK, got info on 2 thermostats
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for 'Upstairs', 311079255724
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Landon's Room', C4FS
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Brooklyn's Room', QJ4X
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Madelyn's Room', QJ4Q
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for 'Downstairs', 511858732763
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Master Bedroom', DNYC
   Ecobee 2 Debug                  Ecobee Downstairs: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs Remote - Madelyn's Room: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs Remote - Landon's Room: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs Remote - Brooklyn's Room: Updating device
   Ecobee 2 Debug                  Landon - Tempature: Updating device
   Ecobee 2 Error                  updatable: Error obtaining ecobee account object
   Ecobee 2 Debug                  Master Bedroom Tempature: Updating device
   Ecobee 2 Error                  updatable: Error obtaining ecobee account object
   Ecobee 2 Debug                  Ecobee Downstairs Remote - Master Bedroom: Updating device
   Ecobee 2 Error                  updatable: Error obtaining ecobee account object
`

**Comment by mrstacey1284** [comment]
Oct 27, 2020 at 12:18:12 PM
   Ecobee 2 Debug                  logLevel = 10
   Ecobee 2 Debug                  updateFrequency = 900.0
   Ecobee 2 Debug                  setting temperature scale to F
   Ecobee 2 Debug                  Ecobee Account (1064672344): Ecobee Account Update OK, got info on 2 thermostats
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for 'Upstairs', 311079255724
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Landon's Room', C4FS
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Brooklyn's Room', QJ4X
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Madelyn's Room', QJ4Q
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for 'Downstairs', 511858732763
   Ecobee 2 Debug                  Ecobee Account (1064672344): getting data for remote sensor 'Master Bedroom', DNYC
   Ecobee 2 Debug                  Ecobee Downstairs: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs Remote - Madelyn's Room: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs Remote - Landon's Room: Updating device
   Ecobee 2 Debug                  Ecobee Upstairs Remote - Brooklyn's Room: Updating device
   Ecobee 2 Debug                  Landon - Tempature: Updating device
   Ecobee 2 Error                  updatable: Error obtaining ecobee account object
   Ecobee 2 Debug                  Master Bedroom Tempature: Updating device
   Ecobee 2 Error                  updatable: Error obtaining ecobee account object
   Ecobee 2 Debug                  Ecobee Downstairs Remote - Master Bedroom: Updating device
   Ecobee 2 Error                  updatable: Error obtaining ecobee account object

**Comment by FlyingDiver** [comment]
Do you have some duplicate devices?  Or old ones?  Because 'Upstairs Remote - Landon's Room' seems fine, but there's an error on ' Landon - Tempature'.  Also 'Master Bedroom Tempature' and 'Downstairs Remote - Master Bedroom'

**Comment by mrstacey1284** [comment]
*FACEAPLM*

I use to have my remote temperature and occupancy broken out into different devices and forgot to delete them. I swear I tried to solve this problem without bugging you. I am sorry.

**Comment by FlyingDiver** [comment]
So all good now?

**Comment by mrstacey1284** [comment]
Yes sir! Thank you for the prompt response.
