### ISSUE TITLE
Temperature scaling not working right

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Ecobee-2#12]
The plug-in is v 2.2.5
I re-authenticated my ecobee account.
There was another anomaly just prior to the token expiration - perhaps related? - as follows: I have an Indigo control page that I use to alter the thermostat settings with 2 buttons, +1C, and -1C (using two action groups). (I confirmed the accuracy of the two action groups). The +1 button changed the setting +11C and I couldn't alter that setting with the -1 button,; resetting to 20C at the thermostat, the -1 changed the setting appropriately twice, and then stopped. I was able to reproduce the behavior.
Trying again now, the +1 button produced:

```
   Ecobee 2                        fHall Thermostat: set heat to: 57.2 and leave cool at: 18.3
   Ecobee 2 Error                  Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 656, in actionControlThermostat
  File "plugin.py", line 787, in handleChangeSetpointAction
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Ecobee 2.indigoPlugin/Contents/Server Plugin/ecobee_devices.py", line 224, in set_hold_temp
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Ecobee 2.indigoPlugin/Contents/Server Plugin/ecobee_account.py", line 229, in make_request
AttributeError: EcobeeAccount instance has no attribute 'access_token'
```

I confirmed that the plug-in is currently authenticated. 
Turning on Detailed Debugging, and pressing the +1 button produces:

```
 Nov 16, 2020 at 3:18:05 PM
   Ecobee 2 Debug                  logLevel = 5
   Ecobee 2 Debug                  updateFrequency = 900.0
   Ecobee 2 Debug                  setting temperature scale to C
   Ecobee 2 Debug                  fHall Thermostat: action.thermostatAction: IncreaseHeatSetpoint
   Ecobee 2                        fHall Thermostat: set heat to: 57.2 and leave cool at: 18.3
   Ecobee 2 Error                  Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 656, in actionControlThermostat
  File "plugin.py", line 787, in handleChangeSetpointAction
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Ecobee 2.indigoPlugin/Contents/Server Plugin/ecobee_devices.py", line 224, in set_hold_temp
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Ecobee 2.indigoPlugin/Contents/Server Plugin/ecobee_account.py", line 229, in make_request
AttributeError: EcobeeAccount instance has no attribute 'access_token'
```

I reloaded the plugin, pressed +1, and it changed the thermostat (iOS) to 57.2F; pressed a second time, sent it to 95F, and a minute lated to 22.9 (Having started at 13C, the correct value would be 15C).  Pressed the -1C and it went to 95.0F, changing after a minute to 21.9C (so perhaps the 95.0F is some temporary value pending a conversion to C?).

Attempting to change the setting in Indigo>Device by pressing the down button produces a similar result:
```
Nov 16, 2020 at 3:26:03 PM
   Ecobee 2 Debug                  fHall Thermostat: action.thermostatAction: DecreaseHeatSetpoint
   Ecobee 2                        fHall Thermostat: set heat to: 71.42 and leave cool at: 18.3
   Ecobee 2 Debug                  API 'set hold temp' request completed, result = <Response [200]>
   Trigger                         fHallStatSetPt2var
   Ecobee 2 Debug                  fHall Thermostat: action.thermostatAction: DecreaseHeatSetpoint
   Ecobee 2                        fHall Thermostat: set heat to: 95 and leave cool at: 18.3
   Ecobee 2 Debug                  API 'set hold temp' request completed, result = <Response [200]>
   Trigger                         fHallStatSetPt2var
   Ecobee 2 Debug                  fHall Thermostat: action.thermostatAction: DecreaseHeatSetpoint
   Ecobee 2                        fHall Thermostat: set heat to: 95 and leave cool at: 18.3
   Ecobee 2 Debug                  API 'set hold temp' request completed, result = <Response [200]>
   Ecobee 2 Debug                  fHall Thermostat: action.thermostatAction: DecreaseHeatSetpoint
   Ecobee 2                        fHall Thermostat: set heat to: 95 and leave cool at: 18.3
   Ecobee 2 Debug                  API 'set hold temp' request completed, result = <Response [200]>
   Ecobee 2 Debug                  fHall Thermostat: action.thermostatAction: DecreaseHeatSetpoint
   Ecobee 2                        fHall Thermostat: set heat to: 95 and leave cool at: 18.3
   Ecobee 2 Debug                  API 'set hold temp' request completed, result = <Response [200]>

```

I think this rules out an Action Group issue.
Enough???

_Originally posted by @smuseby in https://github.com/FlyingDiver/Indigo-Ecobee-2/issues/11#issuecomment-728400308_

**Comment by FlyingDiver** [comment]
This code is all held over from the original Ecobee plugin.  There's no reason to support Kelvin and Rankin (other than pure geek-dom) and there's no reason for this to be handled in ecobee_devices.py.  The Ecobee does everything in scaled Fahrenheit, so all the C/F conversion should be done in the main plugin code.  And maybe the scaling too.

**Comment by smuseby** [comment]
I changed the preference to F, and didn't notice any change when changing
settings with iphone indigo.
Next week, I'll be at our 2nd home, and can test my other ecobee
thermostat. I don't want to fuss with it remotely given the unpredictable
behavior.
Bob

**Comment by smuseby** [comment]
I recently lost power in the mountains (2nd home) for about 30 minutes and
the thermostat authentication survived.

**Comment by FlyingDiver** [comment]
Please make sure you're commenting on the right issue.  The authentication issue is #11. This one is for the temperature scaling issues.

**Comment by FlyingDiver** [comment]
I will be fixing this, but it's not a burning priority.

**Comment by smuseby** [comment]
I have abandoned Celsius for Farenheit, and am using the scaling to modify a scheudled comfort setting. I'm accessing an action group from a control page; the Action Group has one line - for +1F, it's type (Increase Heat Setpoint), device (my thermostat), delta (1). It works to change the thermostat setting, but the new thermostat setting is sticky, overriding subsequent scheduled settings in the Ecobee thermostat itself. There must be a way to avoid this issue - but I'm stuck.

**Comment by FlyingDiver** [comment]
In the config dialog for the thermostat, what do you have the "Default Hold Type" set to?   I think you need to set it to "Next Transition" to have a subsequent transition (schedule change) take effect.  Otherwise a temperature set command sets an indefinite hold on the temp.

**Comment by FlyingDiver** [comment]
There's also an action available to change that setting, if you want to use it to set something that will stick.

**Comment by FlyingDiver** [comment]
And again, this is not actually about temperature scaling, so I'm going to delete all these comments once you read them.

**Comment by smuseby** [comment]
In the Ecobee website, under Settings > Preferences > Hold Action, I have
"Until the next scheduled activity".
It must be somewhere else.

**Comment by FlyingDiver** [comment]
I'm talking about the Indigo Ecobee thermostat device.

**Comment by smuseby** [comment]
The setting in Indigo was "indefinite" - I've changed to "next transition".
I thought it was a scaling issue because the setpoint was sticky only for
the increment/decrement commands, and not for changing the comfort level
setting. It's curious that the Indigo setting overrides the ecobee native
setting.
Should be good now.
Thanks.

**Comment by FlyingDiver** [comment]
Changing a comfort setting is Ecobee's normal operational mode.  Changing a set point is not.  When you change the setpoint (overriding the comfort level), that's really a "hold".  Looking at the thermostat will show it's in a 'hold' state.  When you set a hold on the Ecobee (via the API) you can specify whether it's permanent (indefinite) or temporary (until next transition).  That setting sets the default.  If you do your changes with the defined Ecobee actions (not the default thermostat controls), you can override that setting just for that change.

**Comment by FlyingDiver** [comment]
And since most of this issue not actually about the temperature scaling problems, I'm closing it.  Scaling issues are now #18.
