### ISSUE TITLE
The PIN code field remains blank.

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Ecobee-2#14]
Event log after 'get code' in 'edit device settings' for ecobee account. - the code field remains blank. This looks like my kind of error...

> Jan 8, 2021 at 8:04:31 PM
   Ecobee 2 Error                  Error in plugin execution UiAction:

Traceback (most recent call last):
  File "plugin.py", line 592, in request_pin
AttributeError: EcobeeAccount instance has no attribute 'dev'

_Originally posted by @smuseby in https://github.com/FlyingDiver/Indigo-Ecobee-2/issues/11#issuecomment-757091666_

**Comment by FlyingDiver** [comment]
This is with the newest (debug) version?  Does it work with the previous version?  All I changed was logging, so I wouldn't think that would be the case.  But I'll look at the code again in the morning.

**Comment by FlyingDiver** [comment]
Yeah, my bad.  Good news is, this prompted me to fix an old bug when editing existing devices.

Fixed in 2.3.0

**Comment by smuseby** [comment]
Download file from the Indigo plugin store is Ecobee.2.indigoPlugin.zip;
unzipped reveals Ecobee 2.10.indigoPlugin from Nov 28 2017 date. I don't
see a ver 3. Currently installed is 2.2.8.

**Comment by FlyingDiver** [comment]
The plugin store download has the correct version.  I just checked.  Ignore the date of the plugin wrapper, that doesn't change when I update the code.  If you got a file named **Ecobee 2.10.indigoPlugin** when you unzipped it, you did something wrong.  Like you had an old one in the directory.

**Comment by smuseby** [comment]
The plugin shows up as Ecobee.2 - my mistake was confusing the thermostat
version with the plugin version. Maybe label the plugin file Ecobee2
instead of Ecobee.2.
Proceeding with the upgrades.

**Comment by FlyingDiver** [comment]
GitHub is adding the '.' in place of the space in the zip file.  When you unzip it, the name is correct.

**Comment by smuseby** [comment]
v3 of the plugin installed; each site authenticated with ecobee plugin at
other site disabled; configured to informational.

**Comment by FlyingDiver** [comment]
I assume you actually mean 2.3.0.  ;)

**Comment by smuseby** [comment]
The other thing that made me wonder if I was getting the right version is
the plug-in store showed 0 downloads of the new release.

**Comment by smuseby** [comment]
yes.

**Comment by FlyingDiver** [comment]
I don't think that counter is actually updated.

**Comment by FlyingDiver** [comment]
Are you seeing the messages about the refresh tokens? About every 45 minutes.

**Comment by smuseby** [comment]
I checked 1500-1600, and nothing obvious. searched for "ecobee, 'refresh'
and 'token', and nothing.

**Comment by FlyingDiver** [comment]
I just remembered, it's only going to log when the refresh token changes.  Ecobee says that shouldn't happen, but obviously there's something going on with your system they don't understand.  But it should be easy to find if/when you loose authentication again.  If/When it does happen, grab the logs for both systems for a couple hours before that and see if there's anything logged.

**Comment by FlyingDiver** [comment]
And this is in the wrong issue, again.  Sigh.
