### ISSUE TITLE
OK to create an issue of personal interest only here?

### ISSUE THREAD

**Issue by smuseby** [FlyingDiver/Indigo-Ecobee-2#15]
If not, please delete, and let me know.
Thanks to the python script, I have identified a strange Indigo/Phidgets behavior that has been vexing me.
To get around the ecobee minimum temp setting of 7C, I manage the heater mode with a phidgets temperature sensor in the living room. I have set it to turn the mode on at <4C - and the behavior has been to turn it on at <3C. Per the log created with the python script, I can see the problem:

>  13 18:00, 5.3
 13 18:00, 5.3
 13 18:00, 6.2
 13 20:40, 5.8
 13 23:02, 5.3
 14 00:00, 4.2
 14 00:00, 5.3
 14 00:00, 5.3
 14 01:29, 4.9
 **14 03:59, 4.4
 14 06:00, 2.4
 14 06:04, 4.9**
 14 06:05, 5.3
 14 06:06, 5.8
 14 06:07, 6.2
 14 06:09, 6.7
 14 06:11, 7.1
 14 06:16, 6.7
 14 06:19, 6.2
 14 06:28, 5.8
 14 07:25, 5.3
 14 08:08, 4.9
 **14 09:10, 4.4
 14 12:00, 2.4**
As you may recall, the script records the time/temp every time the temp changes (.4, .5 granularity unless dropping from 4.4 or rising from 2.4). The script is triggered by any change in the phidget device temp. 
Because the temp change below 4C to 3.x isn't being recorded, it explains why the trigger to turn the heater mode to 'on' is not happening until the temperature drops to 2.x.
I have no idea what is going on.
Any thoughts?

**Comment by smuseby** [comment]
I also check all temperatures every 6 hours with a time/date action. The capturing of the temp less than 4 occurs with these events. It's as though the trigger goes on break. Does Indigo have a sleep mode?

**Comment by FlyingDiver** [comment]
Indigo itself doesn't sleep, but if the computer tells it that it's going into sleep mode then Indigo honors that.  But there's usually something in the log about sleeping. 

Why not just run the script on a time schedule instead of a temp change schedule?

**Comment by smuseby** [comment]
A schedule is what's working every 6 hours, and I could change the frequency. But I'm not one to take the easy way - i've been fighting with this for 2-3 months now, puzzled by what wasn't happening. Now I can see the issue, and there must be an explanation. It bugs me that the trigger is not working in this very limited and surprising way.

**Comment by smuseby** [comment]
Nope - it's a bob issue. Cockpit error is always the first thing to
investigate.
