### ISSUE TITLE
Triggers Based on "Last Update"

### ISSUE THREAD

**Issue by IBC-IT** [FlyingDiver/Indigo-Ecobee-2#19]
Please add the ability to trigger Indigo whenever the thermostats are updated.

In practice, what I am trying to accomplish is monitor whether a thermostat is operating "on schedule" or manual override.
So if the temperate is changed manual, outside the schedules comfort settings, Indigo would be aware of this.
If this is possible to do in a simpler fashion, please advise.

**Comment by FlyingDiver** [comment]
Next release has a "last_update" state for the Ecobee Account device.  Triggering on any changes to that device state can be used check if the setpoints have changed.

**Comment by FlyingDiver** [comment]
Individual thermostat devices also have a "lastestEventType" state which can be monitored for changes to/from a "hold" event.
