### ISSUE TITLE
Errors with Cor thermostats

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Ecobee-2#2]
Traceback (most recent call last):
File "plugin.py", line 141, in runConcurrentThread
File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/Ecobee 2.indigoPlugin/Contents/Server Plugin/ecobee.py", line 538, in update
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by shumonsharif** [comment]
Please find requested info here:

[ecobee-2.log](https://github.com/FlyingDiver/Indigo-Ecobee-2/files/2545301/ecobee-2.log)

**Comment by FlyingDiver** [comment]
Try this version:  https://github.com/FlyingDiver/Indigo-Ecobee-2/releases/tag/2.1.1

**Comment by shumonsharif** [comment]
Hi Joe, I was able to get the plugin working with the following changes to ecobee.py (starting at line 221).

```python
                elif remote["type"] == "monitor_sensor":
                    internal = {}
                    for cap in remote["capability"]:
                        if cap["type"] == "occupancy":
                                internal[cap["type"]] = cap["value"]
                    self.thermostats[identifier]["internal"] = internal
```

It's been running flawlessly so far -- I think this should address the outstanding Cor related issues; nice work Joe, and thanks so much as always.

**Comment by FlyingDiver** [comment]
OK, try this one:

https://github.com/FlyingDiver/Indigo-Ecobee-2/releases/tag/2.1.2
