### ISSUE TITLE
Aux Heat Status

### ISSUE THREAD

**Issue by SearchCz** [FlyingDiver/Indigo-Ecobee-2#22]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up a notification (in Indigo 2021.1) whenever my thermostat is calling for Aux Heat.  My "old" thermostat had a physical indicator light that made it obvious to occupants that the (costly) AUX heat was in operation. I want to replicate this somewhat via my smarthome installation. 

**Describe the solution you'd like**
Ideally, I would want to see *AuxHeat* included among the Operation Modes and also among the A/C Equipment States. I would then be able to use these device states to trigger appropriate actions.

**Describe alternatives you've considered**

**Comment by FlyingDiver** [comment]
The Operation modes (in the UI) are determined by the base Thermostat class in Indigo, so I can't add another mode there.  I can make the actual mode available as a custom device state, which you can trigger on.

**Comment by FlyingDiver** [comment]
Released in 2.4.1.

**Comment by SearchCz** [comment]
Thank you ! I will give this a shot tomorrow. Maybe Matt or Jay would  work in some accommodation for AUX heat into a future release as well.
