### ISSUE TITLE
Ecobee errors in event log

### ISSUE THREAD

**Issue by smuseby** [FlyingDiver/Indigo-Ecobee-2#26]
I'm getting the following error message every 10 seconds. Don't know what it means but because 'ecobee' is mentioned, I'm sending the issue to you:

>    Ecobee 2 Error                  Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 140, in runConcurrentThread
AttributeError: 'Plugin' object has no attribute 'next_update'

   Ecobee 2 Error                  plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**To Reproduce**
seems to be spontaneous.

**Expected behavior**
No error message

**Versions (please complete the following information):**
 - MacOS version  11.2.3
 - Indigo version  2021.1.1
 - Plugin version  v2.3.0

**Additional context**

**Comment by FlyingDiver** [comment]
Current plugin version is 2.4.2
