### ISSUE TITLE
Celsius

### ISSUE THREAD

**Issue by smuseby** [FlyingDiver/Indigo-Ecobee-2#30]
**Describe the bug**
Inconsistent set point result when  adding or subtracting 1 degree
**To Reproduce**
1. Go to 'execute an action group that changes setpoint by either plus or minus 1 degree (no units specified'
4. See error There's no error report. When adding 1 degree (6 times), starting at 20C, the results are 20.6, 20.6, 21.1, 21.7, 21.7, 22; when subtracting 1 degree from 20C, the results are 18.9, 17.8, 17.8, 16.7, 16.7, 15.6. To execute an action group for 20C after executing a + or - action, it reguires the 20C action group to be executed twice.

**Expected behavior**
Changing the setpoint  by one degree from 20C should result in 21, 22, 23, or 19, 18,17, etc. Ideally, I'd like the option of changing the setpoint by .5 degrees.

**Screenshots**

**Versions (please complete the following information):**
 - MacOS version  10.14.6
 - Indigo version    2022.1
 - Plugin version    Ecobee 2, v2022.0.0..

**Additional context**
Earlier, there was no support for Celsius. Today, I switched from F to C, renewed my authentication, and reloaded the plug-in. I found no setting within Indigo for C or F units. Indigo seems to respond to the Ecobee setting for unit.

**Comment by FlyingDiver** [comment]
The Ecobee thermostats are F native (actually scaled F - 0.1 degree).  To present C to user, the plugin has to convert from C to (scaled) F and back again.  So those are the scaled numbers you're seeing. 

The Indigo UI only does whole units.  Nothing the plugin can do to change that.

**Comment by smuseby** [comment]
Shocking that a Canadian company would make Fahrenheit native. Sellout.

**Comment by FlyingDiver** [comment]
I could do the rounding, but I'm not convinced it's worth the effort.  And I think that the reason you sometimes see duplicate values after a change is that you're doing it faster than the plugin can communicate with the thermostat server (cloud based API) so the internal value isn't updated in time.

**Comment by smuseby** [comment]
Actually, I noticed the two values for each execution, and waited for the second. 

> 



> Much bigger market.

As I said, sell out.

**Comment by FlyingDiver** [comment]
I am unable to replicate the reported behavior.  I set up an Indigo action group to set the setpoint to 20C, then increment it by 1C multiple times, with a 3 sec delay between each action.  The Indigo UI showed the correct setpoints as the action group executed.
