### ISSUE TITLE
Ability to switch between 'normal' heating mode and Aux Only heating mode.

### ISSUE THREAD

**Issue by lagegel** [FlyingDiver/Indigo-Ecobee-2#31]
Because of where my house is located my Ecobee Premier gets lousy weather data. The outside temperature can often be off by 5-10 degrees. Normally you would depend on the setting of the minimum outdoor temperature for the compressor (in my case 35 degrees) to switch to using gas only so the heat pump doesn't run forever trying to warm the house. Unfortunately I've had nights where the temperature at my house was 30 and the Ecobee thought it was in the 40's because the weather data is so lousy. So, my heat pump runs in vain when my gas heat should be on.

What I would like to do is get the temperature from my personal weather station (which I can do with the WeatherFlow plug-in) and use that temperature to switch the thermostat between the heat and aux heat modes depending on the outdoor temperature. There doesn't seem to be an option in either the standard thermostat settings or the ecobee plug-in settings to turn on aux-heat mode. Am I missing it? If not, would it be possible to add it?

When the Ecobee is set to Aux Heat Mode, the hvacMode=auxHeatOnly

**Comment by robkap** [comment]
I have a similar need related to Aux (gas) heat. 
I have an ecobee Premium. Thanks for adding support for that!
I'd like to run the gas heat based on several factors, such as the outdoor temp, the time, the indoor temp (or the difference between indoor temp and set point).

Specific example: 

If I've set the Sleep temp to 60 and in the morning I want to flash the house up quickly to 68 or 69, I need to run the Aux heat for a little while in the morning, then switch back to heat pump when it's at temp, or close to it, or maybe only for a certain amount of time if gas is expensive. Any suggestions on how to accomplish this?  Maybe there needs to be a configuration settings like:

"Run Aux Heat when indoor temp is below the set point by: ___ degrees" (and also if it's below ___ degrees outside). 
"Max runtime for Aux heat if above heat pump threshold: ___ hours/minutes". 

I'm on the fence if I want this to be time-bound, e.g. only do this in the morning between 6am and 9am. Thoughts?

**Comment by FlyingDiver** [comment]
New plugin specific action added in 2022.1.0 to select heating mode.

**Comment by FlyingDiver** [comment]
@robkap The action you need to force aux heat is now available.  The logic you need can be done in Indigo, and is outside the scope of this issue.
