### ISSUE TITLE
Set fan hold option?

### ISSUE THREAD

**Issue by dan-gearscodeandfire** [FlyingDiver/Indigo-Ecobee-2#32]
**Is your feature request related to a problem? Please describe.**
I would like the plugin to use the "set fan hold" option from the app. 

**Describe the solution you'd like**
I would like to create an action group that, when executed, sets the fan hold to one hour so that the fans are run regardless of whether the air-conditioning handler is on (my unit does not supply heat).

**Describe alternatives you've considered**
I could not think of any kludges to do this.

**Additional context**
Hi Joe,

I am not sure how big a request  this is:

 The ego be app as a screen that allows me to run the fans for 15 minutes 30 minutes, 45 minutes, etc.

 This feature is very wife friendly during the winter, as it cools off the bedrooms without turning the air conditioners on (we have steam radiators for heat on a separate  thermostat).

How challenging would it be for you to add (or  possibly for me to add)  functionality to  set fan hold to one hour?

**Comment by FlyingDiver** [comment]
Did a little research on this.  What the app is doing isn't part of the API.  That is, there's no specific API function to turn on the fan for a specific period of time.

What you want to do is have an action group that does a normal fan mode = on command, then another delayed action that does the "resume" action.

**Comment by FlyingDiver** [comment]
<img width="487" alt="Screenshot 2024-01-18 at 11 29 36 AM" src="https://github.com/FlyingDiver/Indigo-Ecobee-2/assets/72976/3032794e-4651-45c9-91c7-cb5040a1db0f">

**Comment by dan-gearscodeandfire** [comment]
That's amazing, thank you so much for looking into this Joe! My wife (who is recovering from surgery) will be incredibly happy with this functionality when I make a button do it!Sent from my iPhoneOn Jan 18, 2024, at 11:28 AM, Joe Keenan ***@***.***> wrote:﻿
Did a little research on this.  What the app is doing isn't part of the API.  That is, there's no specific API function to turn on the fan for a specific period of time.
What you want to do is have an action group that does a normal fan mode = on command, then another delayed action that does the "resume" action.

**Comment by dan-gearscodeandfire** [comment]
I got around to trying this- I am not finding: set fan mode "X" to always on. 

I am trying to make the group you described as Ecobee 2 Actions -> ?

The options are:
Resume Program
Resume All Programs
Activate Comfort Setting
Set Default Hold Type
Set Comfort Mode

None of them appear to have a "set fan mode" option... I downloaded the latest version for you git... any thoughts? I really appreciate it.

**Comment by FlyingDiver** [comment]
It's not an Ecobee specific action, it's a standard Indigo Thermostat action.  Just like setting a temp setpoint.

<img width="546" alt="Screenshot 2024-02-02 at 4 07 08 PM" src="https://github.com/FlyingDiver/Indigo-Ecobee-2/assets/72976/4b947856-7136-464b-8bce-fa5fc2412be8">

**Comment by dan-gearscodeandfire** [comment]
Never even ocurred to me- thank you as always!
