### ISSUE TITLE
Weekly Token Issues

### ISSUE THREAD

**Issue by mrstacey1284** [FlyingDiver/Indigo-Ecobee-2#6]
I love the plugin and am excited to see Ecobee support active again. I am having one small issue, however. At least once a week I have to refresh my token. I get the following error in the log. 
`API 'set climate hold' request failed, result = {
  "status": {
    "code": 14,
    "message": "Authentication token has expired. Refresh your tokens. "
  }
}
`

**Comment by mrstacey1284** [comment]
I thought I was on the latest, but you're moving so quick I can't keep up. I just upgraded from 2.1.2 to 2.1.7. 

It's always the exact message because I have a trigger set to activate a custom climate hold when the door is left open for more than 10 mins. With 3 kids this happens daily. It sends my wife and I a warning message at 5min which normally prompts the "SHUT THE DOOR!!" warning to the kids and then actives the custom climate hold at 10min.

I get the below message when I reset the token manually, but I haven't seen "Token Request with refresh_token" anywhere. I've also haven't had debugging turned on (only warning) so I'll keep an eye on the logs now. Hopefully the update will fix it.

` Ecobee 2 Debug                  Token Request OK, access_token = LMrKD1lkD3faaXgSg2E3KPLAuE3W1SGo, refresh_token = wVpsY6NoFiofcOvJHKs1IzIoKvtvaBPk, expires_in = 3599`

Also, how do you paste your code into a separate scrollable box?

**Comment by FlyingDiver** [comment]
> Also, how do you paste your code into a separate scrollable box?

Here on GitHub?  Put ```` on the lines before and after the 'code' block.

**Comment by FlyingDiver** [comment]
Oops. Hit the wrong button.

**Comment by mrstacey1284** [comment]
We can close the ticket, hopefully upgrading took care of it. If I continue to have the problem I can open another ticket regarding that version. Thanks for your help!

**Comment by FlyingDiver** [comment]
I think I did find something in the code that might be related.  Leaving this open for now.

**Comment by mrstacey1284** [comment]
FYI... I am seeing this about every 45min now in the log:
````
Ecobee 2 Debug                  Token Request with refresh_token = mu4VkopIuMJGWo0hWGkmXebdnnICTno9 
Ecobee 2 Debug                  Token Refresh OK, access_token = wovU7AQnpZAWyyZhbloi7KIOKtNI1Hee, refresh_token = 7oaOgTVbVJhEavJP6mxc79mcOMZ5ZAa7, expires_in = 3599
````
And thanks for the Markdown tip, the scrolling box look much neater.

**Comment by FlyingDiver** [comment]
That's as expected.  It's when that stops we have a problem.

The access token is good for 3599 seconds (~1 hour).  I refresh at 80% useful life so that if it fails I can try again before it expires.
